name: Build LaTeX PDF

on:
  push:
    branches:
      - paper/**
      - main
      - master
    paths:
      - 'docs/paper/**'
      - '.github/workflows/latex.yml'
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile main.tex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: docs/paper/main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: docs/paper/main.pdf

      - name: Compile results.tex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: docs/paper/results.tex

      - name: Upload Results PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: results-pdf
          path: docs/paper/results.pdf

      - name: Compile ieee_pd_gait.tex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: docs/paper/ieee_pd_gait.tex

      - name: Upload User Paper PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: ieee-pd-gait-pdf
          path: docs/paper/ieee_pd_gait.pdf
