name: Build LaTeX PDF

on:
  push:
    branches:
      - paper/**
      - main
      - master
    paths:
      - 'docs/paper/**'
      - '.github/workflows/latex.yml'
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: docs/paper/main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: docs/paper/main.pdf
